import { StyleSheet } from "react-native";

const C = {
  bg: "#FDFCFB",
  white: "#FFFFFF",
  ink: "#1A1A2E",
  inkMid: "rgba(26,26,46,0.62)",
  inkLight: "rgba(26,26,46,0.36)",
  inkFaint: "rgba(26,26,46,0.08)",
  rose: "#FF4E7A",
  roseDeep: "#E83266",
  roseTint: "#FFE8EE",
  roseSoft: "#FFF4F7",
  roseBorder: "#FFD1DD",
  lav: "#8B5CF6",
  lavTint: "#F3EEFF",
  tealTint: "#E6FAFA",
  danger: "#B91C1C",
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: C.bg,
  },
  keyboardAvoid: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 34,
    paddingBottom: 10,
  },
  header: {
    paddingBottom: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
  },
  kicker: {
    color: C.rose,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 3,
  },
  title: {
    marginTop: 2,
    color: C.ink,
    fontSize: 34,
    fontWeight: "900",
    lineHeight: 38,
  },
  headerBadge: {
    minWidth: 54,
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: C.roseBorder,
    backgroundColor: C.white,
    marginTop: 8,
  },
  headerBadgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: C.rose,
  },
  headerBadgeText: {
    color: C.ink,
    fontWeight: "900",
    fontSize: 13,
  },
  section: {
    minHeight: 74,
    marginBottom: 12,
  },
  horizontalList: {
    marginHorizontal: -20,
  },
  conversationListContent: {
    paddingHorizontal: 20,
    gap: 10,
    paddingBottom: 4,
  },
  conversationItem: {
    width: 166,
    minHeight: 66,
    padding: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.roseBorder,
    backgroundColor: C.white,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  conversationItemSelected: {
    borderColor: C.rose,
    backgroundColor: C.roseSoft,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.roseTint,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarGroup: {
    backgroundColor: C.lavTint,
  },
  avatarText: {
    fontSize: 12,
    fontWeight: "900",
    color: C.ink,
  },
  conversationCardBody: {
    flex: 1,
    minWidth: 0,
  },
  conversationTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  conversationTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: "900",
    color: C.ink,
  },
  conversationType: {
    marginTop: 2,
    marginBottom: 2,
    color: C.roseDeep,
    fontSize: 10,
    fontWeight: "800",
  },
  conversationSnippet: {
    fontSize: 11,
    lineHeight: 15,
    color: C.inkMid,
  },
  unreadBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: C.rose,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  unreadBadgeText: {
    color: C.white,
    fontSize: 10,
    fontWeight: "900",
  },
  chatArea: {
    flex: 1,
  },
  chatPane: {
    flex: 1,
    borderRadius: 24,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.roseBorder,
    overflow: "hidden",
  },
  conversationHeader: {
    minHeight: 62,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.inkFaint,
    backgroundColor: C.white,
  },
  activeConversationTitle: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  conversationHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  avatarSmall: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.tealTint,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarSmallText: {
    fontSize: 12,
    fontWeight: "900",
    color: C.ink,
  },
  conversationHeaderTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: C.ink,
  },
  conversationHeaderMeta: {
    marginTop: 2,
    fontSize: 12,
    color: C.inkMid,
  },
  participantsPanel: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.inkFaint,
    backgroundColor: C.white,
  },
  participantListContent: {
    paddingHorizontal: 16,
    gap: 8,
  },
  participantChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: C.roseSoft,
    borderWidth: 1,
    borderColor: C.roseBorder,
  },
  participantChipText: {
    color: C.roseDeep,
    fontSize: 12,
    fontWeight: "800",
  },
  loadingMessages: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  messageList: {
    flex: 1,
    backgroundColor: "#FFFCFB",
  },
  messageListContent: {
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 10,
  },
  emptyState: {
    margin: 14,
    padding: 20,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.roseBorder,
    backgroundColor: C.white,
    alignItems: "center",
  },
  emptyStateText: {
    color: C.inkMid,
    fontSize: 14,
    textAlign: "center",
  },
  emptyStateTitle: {
    marginBottom: 6,
    color: C.ink,
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
  },
  errorText: {
    color: C.danger,
    fontSize: 13,
    textAlign: "center",
  },
  messageRow: {
    marginBottom: 10,
    maxWidth: "82%",
  },
  messageRowSent: {
    alignSelf: "flex-end",
    alignItems: "flex-end",
    marginLeft: 48,
  },
  messageRowReceived: {
    alignSelf: "flex-start",
    alignItems: "flex-start",
    marginRight: 48,
  },
  messageSender: {
    marginBottom: 4,
    marginLeft: 4,
    color: C.inkLight,
    fontSize: 11,
    fontWeight: "800",
  },
  messageContainer: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
  },
  messageContainerSent: {
    backgroundColor: C.rose,
    borderBottomRightRadius: 6,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 18,
    // subtle shadow to lift sent bubbles
    shadowColor: C.roseDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  messageContainerReceived: {
    backgroundColor: C.lavTint,
    borderWidth: 0,
    borderRadius: 18,
    borderBottomLeftRadius: 6,
  },
  messageText: {
    color: C.ink,
    fontSize: 14,
    lineHeight: 20,
  },
  messageTextSent: {
    color: C.white,
    textAlign: "right",
  },
  messageMeta: {
    marginTop: 5,
    fontSize: 10,
    color: C.inkLight,
    textAlign: "right",
  },
  messageMetaSent: {
    color: "rgba(255,255,255,0.88)",
  },
  composer: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: C.inkFaint,
    backgroundColor: C.white,
  },
  composerRow: {
    minHeight: 50,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    padding: 5,
    borderRadius: 18,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.roseBorder,
  },
  messageInput: {
    flex: 1,
    minHeight: 40,
    paddingHorizontal: 12,
    color: C.ink,
    fontSize: 14,
  },
  sendButton: {
    minWidth: 76,
    height: 40,
    borderRadius: 14,
    backgroundColor: C.rose,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  sendButtonText: {
    color: C.white,
    fontSize: 14,
    fontWeight: "900",
  },
});
