import { StyleSheet } from 'react-native';

const C = {
  bg: '#FDFCFB',
  white: '#ffffff',
  ink: '#1A1A2E',
  inkMid: 'rgba(26,26,46,0.62)',
  inkLight: 'rgba(26,26,46,0.35)',
  inkFaint: 'rgba(26,26,46,0.08)',
  rose: '#FF4E7A',
  roseTint: '#FFE8EE',
  roseSoft: '#FFF4F7',
  roseDeep: '#E83266',
  gold: '#FF9B50',
  lav: '#8B5CF6',
  lavTint: '#F3EEFF',
  teal: '#14B8A6',
  tealTint: '#E6FAFA',
  danger: '#b91c1c',
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: C.bg,
    paddingHorizontal: 18,
    paddingTop: 24,
  },
  header: {
    marginBottom: 18,
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  kicker: {
    fontSize: 10,
    letterSpacing: 3,
    color: C.rose,
    fontWeight: '800',
  },
  title: {
    fontSize: 34,
    fontWeight: '900',
    color: C.ink,
    lineHeight: 38,
  },
  description: {
    fontSize: 14,
    color: C.inkMid,
  },
  headerBadge: {
    minWidth: 54,
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderWidth: 1,
    borderColor: 'rgba(255,78,122,0.22)',
    backgroundColor: C.white,
  },
  headerBadgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: C.rose,
  },
  headerBadgeText: {
    color: C.ink,
    fontWeight: '800',
    fontSize: 13,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: C.inkMid,
    marginBottom: 9,
    textTransform: 'uppercase',
  },
  card: {
    borderWidth: 1,
    borderColor: 'rgba(26,26,46,0.08)',
    borderRadius: 16,
    backgroundColor: C.white,
    padding: 12,
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  input: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: C.inkFaint,
    borderRadius: 12,
    paddingHorizontal: 13,
    backgroundColor: '#FFFEFD',
    color: C.ink,
    fontSize: 13,
  },
  inputFlex: {
    flex: 1,
    minWidth: 0,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 10,
  },
  button: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: C.rose,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  buttonText: {
    color: C.white,
    fontSize: 14,
    fontWeight: '800',
  },
  errorText: {
    color: C.danger,
    fontSize: 13,
  },
  horizontalList: {
    marginHorizontal: 0,
  },
  conversationListContent: {
    paddingHorizontal: 0,
    gap: 10,
    paddingBottom: 4,
  },
  conversationItem: {
    width: 184,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(26,26,46,0.08)',
    backgroundColor: C.white,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 1,
  },
  conversationItemSelected: {
    borderColor: 'rgba(255,78,122,0.7)',
    backgroundColor: C.roseSoft,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.roseTint,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  avatarGroup: {
    backgroundColor: C.lavTint,
  },
  avatarText: {
    fontSize: 13,
    fontWeight: '900',
    color: C.ink,
  },
  conversationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 3,
  },
  conversationTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    color: C.ink,
  },
  conversationType: {
    alignSelf: 'flex-start',
    marginBottom: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,78,122,0.12)',
    color: C.roseDeep,
    fontSize: 11,
    fontWeight: '800',
  },
  conversationMeta: {
    marginTop: 7,
    fontSize: 12,
    color: C.inkLight,
  },
  unreadBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: C.rose,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
  },
  unreadBadgeText: {
    color: C.white,
    fontSize: 11,
    fontWeight: '900',
  },
  conversationSnippet: {
    fontSize: 13,
    lineHeight: 18,
    color: C.inkMid,
  },
  chatArea: {
    flex: 1,
    borderTopWidth: 1,
    borderTopColor: 'rgba(26,26,46,0.08)',
    paddingTop: 14,
    marginTop: 2,
  },
  conversationHeader: {
    minHeight: 58,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    gap: 10,
  },
  activeConversationTitle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatarSmall: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: C.tealTint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarSmallText: {
    fontSize: 12,
    fontWeight: '900',
    color: C.ink,
  },
  conversationHeaderTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: C.ink,
  },
  conversationHeaderMeta: {
    marginTop: 2,
    fontSize: 12,
    color: C.inkMid,
  },
  presenceText: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: C.roseTint,
    fontSize: 12,
    fontWeight: '800',
    color: C.roseDeep,
  },
  participantsPanel: {
    marginBottom: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(255,78,122,0.12)',
  },
  participantsTitle: {
    marginBottom: 8,
    color: C.inkMid,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  participantListContent: {
    gap: 8,
  },
  participantChip: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: 'rgba(255,78,122,0.18)',
  },
  participantChipText: {
    color: C.roseDeep,
    fontSize: 12,
    fontWeight: '800',
  },
  messageList: {
    flex: 1,
  },
  messageListContent: {
    paddingVertical: 8,
  },
  emptyState: {
    padding: 22,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(26,26,46,0.08)',
    backgroundColor: C.white,
    alignItems: 'center',
  },
  emptyStateText: {
    color: C.inkMid,
    fontSize: 14,
    textAlign: 'center',
  },
  emptyStateTitle: {
    marginBottom: 6,
    color: C.ink,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  messageContainer: {
    marginBottom: 10,
    maxWidth: '82%',
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: C.white,
  },
  messageContainerSent: {
    alignSelf: 'flex-end',
    backgroundColor: C.rose,
    borderBottomRightRadius: 6,
  },
  messageContainerReceived: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(26,26,46,0.08)',
    borderBottomLeftRadius: 6,
  },
  messageText: {
    color: C.ink,
    fontSize: 14,
    lineHeight: 20,
  },
  messageTextSent: {
    color: C.white,
  },
  messageMeta: {
    marginTop: 6,
    fontSize: 11,
    color: C.inkLight,
    textAlign: 'right',
  },
  messageMetaSent: {
    color: 'rgba(255,255,255,0.62)',
  },
  composer: {
    paddingTop: 12,
    paddingBottom: 8,
  },
  composerRow: {
    minHeight: 52,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    padding: 6,
    borderRadius: 18,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: 'rgba(26,26,46,0.08)',
  },
  messageInput: {
    flex: 1,
    minHeight: 42,
    paddingHorizontal: 12,
    color: C.ink,
    fontSize: 14,
  },
  sendButton: {
    minWidth: 78,
    height: 42,
    borderRadius: 14,
    backgroundColor: C.rose,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sendButtonText: {
    color: C.white,
    fontSize: 14,
    fontWeight: '900',
  },
});
